jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: git submodule update --init
  - script: ./build.sh

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: git submodule update --init
  - script: ./build.sh

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: git submodule update --init
  - powershell: .\build.ps1
