name: Publish IronRe2-Batteries

on:
  release:
    types:
      - published # Run the workflow when a new GitHub release is published
  workflow_dispatch: # Allow manual triggering from the GitHub UI

# Set permissions for the workflow.
permissions:
  contents: write
  packages: write
  checks: write
  pull-requests: write

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget

jobs:
  build:
    uses: ./.github/workflows/ci.yaml

    # Publish only when creating a GitHub Release
    # https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
    # You can update this logic if you want to manage releases differently
  publish:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download Windows Package
        uses: actions/download-artifact@v4
        with:
          name: artifacts-windows
          path: bin/artifacts/Windows/

      - name: Download Linux Package
        uses: actions/download-artifact@v4
        with:
          name: artifacts-linux
          path: bin/artifacts/Linux/

      - name: Download macOS Package
        uses: actions/download-artifact@v4
        with:
          name: artifacts-macos
          path: bin/artifacts/macos/

      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      # Publish all NuGet packages to NuGet.org
      # Use --skip-duplicate to prevent errors if a package with the same version already exists.
      # If you retry a failed workflow, already published packages will be skipped without error.
      - name: Publish NuGet Packages to GitHub Packages
        run: dotnet nuget push bin/artifacts/**/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate



